spring.application.name=ms-eureka
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.root=INFO
logging.level.ms_eureka=DEBUG
logging.file.name=logs/ms-eureka.log